todo-application/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
namespace todo_application.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext()
        {

        }
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {

        }

        public DbSet<Todo> Todos { get; set; }
    }
}

todo-application/Models/ErrorViewModel.cs
using System;

namespace todo_application.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

todo-application/Models/Todo.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;

namespace todo_application.Models
{
    public class Todo
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Title is required")]
        [StringLength(80, ErrorMessage = "Title must not exceed 100 characters")]
        public string Title { get; set; }
        [StringLength(320, ErrorMessage = "Description must not exceed 320 characters")]
        public string Description { get; set; }
        public DateTime CreatedDate { get; set; } = DateTime.Now;
        [Required(ErrorMessage = "Duedate is required")]
        public DateTime DueDate { get; set; }
        public int Status { get; set; } = 0;
    }
}

todo-application/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using todo_application.Models;

namespace todo_application.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

todo-application/Controllers/TodoController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using todo_application.Models;
using todo_application.Repository;

namespace todo_application.Controllers
{
    public class TodoController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly TodoListRepository _repository;
        public TodoController(ApplicationDbContext context, TodoListRepository repository)
        {
            _context = context;
            _repository = repository;
        }

        public IActionResult Index()
        {
            var model = _context.Todos.Where(x => x.Status != 2).ToList();
            return View(model);
        }

        public IActionResult AddPage()
        {
            return View();
        }

        [HttpGet("{id:int}")]
        public IActionResult UpdatePage(int id)
        {
            Todo model = _context.Todos.Where(x => x.Id == id).FirstOrDefault();
            if(model == null)
            {
                return View("Error");
            }
            return View(model);
        }

        [HttpGet("details/{id}")]
        public IActionResult DetailPage(int id)
        {
            Todo details = _context.Todos.Where(x => x.Id == id).FirstOrDefault();
            return View(details);
        }

        [HttpPost]
        public IActionResult AddTodo(Todo body)
        {
            if (!ModelState.IsValid)
            {
                return View("AddPage");
            }

            _repository.AddTodo(body);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult UpdateTodo(Todo body)
        {
            if (!ModelState.IsValid)
            {
                return View("UpdatePage", body);
            }

             _repository.UpdateTodo(body);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult MarkAsFinished(int id)
        {
            var finish = _repository.ChangeStatus(id, 2);

            if (!finish)
            {
                return Json(new { success = "Something went wrong" });
            }

            return Json(new { success = "Success" });
        }

        [HttpPost]
        public IActionResult ChangeTodoStatus(int id, int status)
        {
            var setDoing = _repository.ChangeStatus(id, status);

            if (!setDoing)
            {
                return Json(new { success = "Something went wrong" });
            }

            return Json(new { success = "Success" });
        }

        [HttpPost]
        public IActionResult DeleteTodo(int id)
        {
            var delete = _repository.DeleteTodo(id);

            if (!delete)
            {
                return Json(new { errorMessage = "Something went wrong" });
            }

            return Json(new { success = "Success" });
        }

        [HttpGet]
        public IActionResult FinishedTodos()
        {
            var model = _context.Todos.Where(x => x.Status == 2).ToList();

            return View(model);
        }

        [HttpPost]
        public IActionResult UnMarkFinished(int id)
        {
            var finish = _repository.ChangeStatus(id, 0);

            if (!finish)
            {
                return Json(new { success = "Something went wrong" });
            }

            return Json(new { success = "Success" });
        }
        
        [HttpGet("Error404")]
        public IActionResult Error()
        {
            return View();
        }
    
    }
}

todo-application/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

todo-application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - todo_application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">todo_application</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Todo" asp-action="Index">Todos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Todo" asp-action="FinishedTodos">Finished Todos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

todo-application/Views/Todo/AddPage.cshtml
@model Todo
<style>
    .add {
        display: float;
        text-align: center;
        margin-top: 5px;
    }

    body {
        font-family: 'Ubuntu', sans-serif;
    }

    .backButton:hover {
        background-color: silver;
        color: white;
    }

    .card {
        width: 22rem;
        border-color: #212529;
        border: 2px solid;
    }
    .card-header{
        background-color: #212529;

    }
    h5{
        color: white;
    }

    #descriptionCharNum, #titleCharNum{
        color: #8f8d88;
        text-align: end;
    }
</style>

<div class="d-flex justify-content-center">

    <form asp-action="AddTodo" asp-controller="Todo" method="post">

        <div class="card">

            <div class="card-header d-flex justify-content-between">
                <h5>Add todo</h5>
                <div class="">
                    <a asp-controller="Todo" asp-action="Index" class="btn btn-primary backButton">
                        <i class="bi bi-arrow-left-circle"></i>
                    </a>
                </div>
            </div>

            <div class="card-body">

                <div class="add">
                    <label asp-for="Title" class="" for="Title">Title</label>
                    <input asp-for="Title" class="form-control"
                    type="text" name="Title" id="Title" placeholder="Title"
                    onkeyup="countTitleChars(this)"/>
                    <p id="titleCharNum">80 characters</p>
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <div class="add">
                    <label asp-for="Description" class="" for="Title">Description</label>
                    <textarea asp-for="Description" class="form-control" type="text"
                    name="Description" id="Description" placeholder="Description"
                    onkeyup="countDescriptionChars(this)"></textarea>
                    <p id="descriptionCharNum">320 characters</p>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="add">
                    <label asp-for="DueDate" class="" for="Title">DueDate</label>
                    <input asp-for="DueDate" class="form-control" type="datetime-local" name="DueDate" id="DueDate" placeholder="DueDate" />
                    <span asp-validation-for="DueDate" class="text-danger"></span>
                </div>

            </div>

            <div class="card-footer d-flex justify-content-end">
                <button type="submit" class="btn btn-info">Add</button>

            </div>

        </div>

    </form>
</div>

<script>
    function countTitleChars(obj){
        document.getElementById('titleCharNum').innerHTML = 80 - obj.value.length + ' characters';
    }

    function countDescriptionChars(obj){
        document.getElementById('descriptionCharNum').innerHTML = 320 - obj.value.length + ' characters';
    }
</script>

todo-application/Views/Todo/DetailPage.cshtml
@model Todo

<script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>

<style>
    body {
        font-family: 'Ubuntu', sans-serif;
    }

    .duedate {
        border: 2px solid;
        border-color: red;
        background-color: #fa6e4b;
        display: inline;
        padding: 3px;
    }

    .card {
        border-color: #212529;
        border: 2px solid;
    }
    .card-header{
        background-color: #212529;

    }

    a > i:hover {
        color: white;
    }

    .descriptionHeader,.description{
        border-bottom: 1px solid;
        border-color: silver;
        padding-bottom: 10px;
    }
</style>

<div class="container">
    <div class="card">

        <div class="card-header d-flex justify-content-between">
            <h5 style="color: white;">@Model.Title</h5>
            <div class="">
                <a asp-controller="Todo" asp-action="Index" class="btn btn-primary backButton">
                    <i class="bi bi-arrow-left-circle"></i>
                </a>
            </div>
        </div>

        <div class="card-body">
            <h5 class="descriptionHeader">Description</h5>
            <p class="description">@Model.Description</p>
            <p>
                Status -
                @if (Model.Status == 0)
                {
                    <i class="bi bi-flag">Not started</i>
                }
                else if (Model.Status == 1)
                {
                    <i class="bi bi-flag-fill">In Process</i>
                }
                else
                {
                    <i class="bi bi-flag-fill">Finished</i>
                }
            </p>
        </div>

        <div class="card-footer d-flex justify-content-between">
            <p class="duedate">@Model.DueDate</p>
            <p>
                <a class="btn btn-info doingButton" data-id="@Model.Id" data-status="@Model.Status">
                    @if (Model.Status == 0)
                    {
                        <i class="bi bi-flag-fill">Mark as doing</i>
                    }
                    else
                    {
                        <i class="bi bi-flag">Mark as todo</i>
                    }
                </a>
            </p>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $(".doingButton").on('click', function() {
             var itemId = $(this).data("id");
             var checkStatus = $(this).data("status");

             if(checkStatus == 0){
                var d = {id: itemId, status: 1};
             }else{
                var d = {id: itemId, status: 0};
             }

             $.ajax({
                 type: 'POST',
                 url: '@Url.Action("ChangeTodoStatus", "Todo")',
                 data: d,
                 success: function(data){
                     if(data.success == "Success"){
                        location.reload();
                     }
                     else{
                         alert("something went wrong");
                     }
                 }
             });
        });
    });
</script>

todo-application/Views/Todo/FinishedTodos.cshtml
@model List<Todo>

<script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>

<style>

    body {
        font-family: 'Ubuntu', sans-serif;
    }

    .updateButton:hover {
        background-color: green;
    }

    .delButton:hover {
        background-color: red;
        color: white;
    }

    .doingButton:hover {
        background-color: blue;
    }

    .detailsButton:hover{
        background-color: silver;
    }

    a > i:hover {
        color: white;
    }

    .taskCard {
        border-bottom: 1px solid;
        border-color: silver;
        justify-content: start;
    }

    .taskCard:hover {
        border: 2px solid;
        border-color: silver;
    }    

    .taskCard-element {
        margin-top: 10px;
    }

    .itemId {
        height: 20px;
        width: 20px;
    }

    .noTaskHeader{
        text-align: center;
        border: 1px solid;
        border-color: silver;
        width: 100%;
        padding: 10px;
    }
</style>

<div class="container-sm">
    <h1>Completed Todos</h1>

    @if(@Model.Count == 0)
    {
        <h3 class="noTaskHeader">You haven't finished any tasks</h3>
    }

    @foreach (var item in @Model)
    {
        <div class="taskCard row">
            <input type="checkbox" @(item.Status == 2 ? "checked='checked'" : "") value="@item.Id" class="itemId col-md-1 taskCard-element" />
            <h5 class="col-6 taskCard-element">
                @item.Title - <i class="bi bi-cup-straw"></i>
            </h5>

            <div class="dropdown d-flex justify-content-end col">
                <button class="btn btn-sm" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="bi bi-list"></i>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

                    <a href="/details/@item.Id" class="btn btn-sm dropdown-item detailsButton">
                        <i class="bi bi-pencil-square">Details</i>
                    </a>

                    <a asp-controller="Todo" asp-action="UpdatePage" asp-route-id="@item.Id" class="btn btn-sm dropdown-item updateButton">
                        <i class="bi bi-pencil-square">Edit</i>
                    </a>
                    <a class="btn btn-sm dropdown-item delButton" data-id="@item.Id">
                        <i class="bi bi-trash">Delete</i>
                    </a>
                </div>
            </div>

        </div>
    }

    <div class="d-flex justify-content-end">
        <a asp-controller="Todo" asp-action="Index" class="btn btn-lg btn-primary mt-4 goBackButton">
            <i class="bi bi-arrow-left-circle"></i>
        </a>
    </div>

</div>

<script>
    $(document).ready(function(){
        $(".itemId").on('change',function (){
            var itemId = $(this).val();

            var d = {id: itemId};

            $.ajax({
                type: 'POST',
                url: '@Url.Action("UnMarkFinished", "Todo")',
                data: d,
                success: function (data) {
                    if(data.success == "Success"){
                        alert("success");
                        location.reload();
                    }
                    else{
                        alert("something went wrong");
                    }                    
                }
            });
        });

        $(".delButton").on('click', function() {
            var itemId = $(this).data("id");

            var d = {id: itemId};

            var result = confirm("Are you sure you want to delete this item");

            if (result){
                $.ajax({
                    type:'POST',
                    url: '@Url.Action("DeleteTodo", "Todo")',
                    data: d,
                    success: function (data) {
                        if(data.success == "Success"){
                            alert("success");
                            location.reload();
                        }
                        else{
                            alert("something went wrong");
                        }
                    }
                });
            }
        });
    });
</script>

todo-application/Views/Todo/Index.cshtml
@model List<Todo>


<script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>

<style>

    body {
        font-family: 'Ubuntu', sans-serif;
    }

    .updateButton:hover {
        background-color: green;
    }

    .delButton:hover {
        background-color: red;
        color: white;
    }

    .doingButton:hover {
        background-color: blue;
    }

    .detailsButton:hover {
        background-color: silver;
    }

    a > i:hover {
        color: white;
    }

    .taskCard {
        border-bottom: 2px solid;
        border-color: silver;
        justify-content: start;
    }

    .taskCard:hover {
        border: 3px solid;
        border-color: silver;
    }    

    .taskCard-element {
        margin-top: 10px;
    }

    .itemId {
        height: 20px;
        width: 20px;
    }

    .noTaskHeader {
        text-align: center;
        border: 1px solid;
        border-color: silver;
        width: 100%;
        padding: 10px;
    }
</style>

<div class="container-sm">
    <h1>Your Todos</h1>

    @if (@Model.Count == 0)
    {
        <h3 class="noTaskHeader">You dont have any tasks, add some</h3>
    }

    @foreach (var item in @Model)
    {
        <div class="taskCard row">
            <input type="checkbox" @(item.Status == 2 ? "checked='checked'" : "") value="@item.Id" class="itemId col-md-1 taskCard-element" />
            <h5 class="col-6 taskCard-element">
                @item.Title - @if (item.Status == 0)
                {
                    <i class="bi bi-flag"></i>
                }
                else
                {
                    <i class="bi bi-flag-fill"></i>
                }
            </h5>

            @if (item.DueDate < DateTime.Now)
            {
                <div class="d-flex justify-content-end col">
                    <h5 class="overdue taskCard-element">Overdue</h5>
                </div>
            }

            <div class="dropdown d-flex justify-content-end col">
                <button class="btn btn-sm" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="bi bi-list"></i>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

                    <a href="/details/@item.Id" class="btn btn-sm dropdown-item detailsButton">
                        <i class="bi bi-pencil-square">Details</i>
                    </a>

                    <a asp-controller="Todo" asp-action="UpdatePage" asp-route-id="@item.Id" class="btn btn-sm dropdown-item updateButton">
                        <i class="bi bi-pencil-square">Edit</i>
                    </a>
                    <a class="btn btn-sm dropdown-item delButton" data-id="@item.Id">
                        <i class="bi bi-trash">Delete</i>
                    </a>
                    <a class="btn btn-sm dropdown-item doingButton" data-id="@item.Id" data-status="@item.Status">
                        @if (item.Status == 0)
                        {
                            <i class="bi bi-flag-fill">Mark as doing</i>
                        }
                        else
                        {
                            <i class="bi bi-flag">Mark as todo</i>
                        }
                    </a>
                </div>
            </div>

        </div>
    }

    <div class="d-flex justify-content-end">
        <a asp-controller="Todo" asp-action="AddPage" class="btn btn-lg btn-primary addButton mt-4">
            <i class="bi bi-plus-square"></i>
        </a>
    </div>

</div>

<script>

    $(document).ready(function () {

        $(".itemId").on('change',function (){
            var itemId = $(this).val();

            var d = {id: itemId};

            $.ajax({
                type: 'POST',
                url: '@Url.Action("MarkAsFinished", "Todo")',
                data: d,
                success: function (data) {
                    if(data.success == "Success"){
                        location.reload();
                    }
                    else{
                        alert("something went wrong");
                    }
                }
            });
        });

        $(".delButton").on('click', function() {
            var itemId = $(this).data("id");

            var d = {id: itemId};

            var result = confirm("Are you sure you want to delete this item");

            if (result){
                $.ajax({
                    type:'POST',
                    url: '@Url.Action("DeleteTodo", "Todo")',
                    data: d,
                    success: function (data) {
                        if(data.success == "Success"){
                            location.reload();
                        }
                        else{
                            alert("something went wrong");
                        }
                    }
                });
            }
        });

        $(".doingButton").on('click', function() {
             var itemId = $(this).data("id");
             var checkStatus = $(this).data("status");

             if(checkStatus == 0){
                var d = {id: itemId, status: 1};
             }else{
                var d = {id: itemId, status: 0};
             }


             $.ajax({
                 type: 'POST',
                 url: '@Url.Action("ChangeTodoStatus", "Todo")',
                 data: d,
                 success: function(data){
                     if(data.success == "Success"){
                        location.reload();
                     }
                     else{
                         alert("something went wrong");
                     }
                 }
             });
        });
    });

</script>

todo-application/Views/Todo/UpdatePage.cshtml
@model Todo

<style>
    .add {
        display: float;
        text-align: center;
        margin-top: 5px;
    }

    body {
        font-family: 'Ubuntu', sans-serif;
    }

    .backButton:hover {
        background-color: silver;
        color: white;
    }

    .card {
        width: 22rem;
        border-color: #212529;
        border: 2px solid;
    }

    .card-header {
        background-color: #212529;
    }

    h5 {
        color: white;
    }

    #descriptionCharNum, #titleCharNum{
        color: #8f8d88;
        text-align: end;
    }
</style>

<div class="d-flex justify-content-center">

    <form asp-action="UpdateTodo" asp-controller="Todo" method="post">
        <input type="hidden" asp-for="Id" />

        <div class="card">

            <div class="card-header d-flex justify-content-between">
                <h5>Update todo</h5>
                <div class="">
                    <a asp-controller="Todo" asp-action="Index" class="btn btn-primary">
                        <i class="bi bi-arrow-left-circle"></i>
                    </a>
                </div>
            </div>

            <div class="card-body">

                <div class="add">
                    <label asp-for="Title" class="" for="Title">Title</label>
                    <input asp-for="Title" class="form-control"
                           type="text" name="Title" id="Title" placeholder="Title"
                           onkeyup="countTitleChars(this)" />
                    <p id="titleCharNum">80 characters</p>
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <div class="add">
                    <label asp-for="Description" class="" for="Title">Description</label>
                    <textarea asp-for="Description" class="form-control" type="text"
                              name="Description" id="Description" placeholder="Description"
                              onkeyup="countDescriptionChars(this)"></textarea>
                    <p id="descriptionCharNum">320 characters</p>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="add">
                    <label asp-for="DueDate" class="" for="Title">DueDate</label>
                    <input asp-for="DueDate" class="form-control" type="datetime-local" name="DueDate" id="DueDate" placeholder="DueDate" />
                    <span asp-validation-for="DueDate" class="text-danger"></span>
                </div>

            </div>

            <div class="card-footer d-flex justify-content-end">
                <button type="submit" class="btn btn-info">Update</button>
            </div>

        </div>

    </form>
</div>

<script>
    function countTitleChars(obj){
        document.getElementById('titleCharNum').innerHTML = 80 - obj.value.length + ' characters';
    }

    function countDescriptionChars(obj){
        document.getElementById('descriptionCharNum').innerHTML = 320 - obj.value.length + ' characters';
    }
</script>